name: "Terraform Apply"

on:
  #  push:
  #    branches: [ main ]
  workflow_dispatch:

jobs:
  dev:
    name: "Terraform Dev Apply"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY}}

    defaults:
      run:
        shell: bash
        working-directory: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}

      - name: Terraform Init Dev
        run: |
          git config --global url."https://oauth2:${{ secrets.GIT_HUB_TOKEN }}@github.com".insteadOf https://github.com
          terraform init

      - name: Terraform Apply Dev
        run: terraform apply -auto-approve

  prod:
    name: "Terraform Prod Apply"
    needs: dev
    runs-on: ubuntu-latest
    env:
      name: prod
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY}}

    defaults:
      run:
        shell: bash
        working-directory: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}

      - name: Terraform Init Prod
        run: |
          git config --global url."https://oauth2:${{ secrets.GIT_HUB_TOKEN }}@github.com".insteadOf https://github.com
          terraform init

      - name: Terraform Apply Prod
        run: terraform apply -auto-approve
